pipelines:
    - name: Testing_Xray
      steps: 
        - name: test
          type: Bash
          configuration:
            integrations:
                - name: jfrogPat
          execution:
            onExecute:
                - touch test.txt
                - echo "Hello World" > test.txt
                - jfrog s test.txt
