resources:
    - name: build
      type: CronTrigger
      configuration:
        interval: '*/10 * * * *'

pipelines:
    - name: Testing_Xray
      configuration:
          jfrogCliVersion: 2
      steps: 
        - name: test
          type: Bash
          configuration:
            integrations:
                - name: jfrog_platform_embedded_pipelines
            inputResources:
                - name: build
                  trigger: true
          execution:
            onExecute:
                - touch test.txt
                - echo "Hello World" > test.txt
                - jfrog scan test.txt
