pipelines:
    - name: Testing_Artifactory
    steps: 
        - name: test
          type: Bash
          configuration:
            integrations:
                - name: jfrogPat
          execution:
            onExecute:
                - touch test.txt
                - echo "Hello World" > test.txt
                - jf rt u test.txt jfrogpipelines 
                - jf rt dl jfrogpipelines/test.txt
                - jf rt del jfrogpipelines/test.txt
                
