pipelines:
    - name: Testing_Artifactory
      steps: 
        - name: test
          type: Bash
          configuration:
            integrations:
                - name: jfrog_platform_embedded_pipelines
          execution:
            onExecute:
                - touch test.txt
                - echo "Hello World" > test.txt
                - jfrog rt u test.txt jfrogpipelines 
                - jfrog rt dl jfrogpipelines/test.txt
                - jfrog rt del jfrogpipelines/test.txt
                
